spring.application.name=springboot-railway-demo

spring.profiles.default=dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info